<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="NationalInstruments.Visa" Version="25.5.0.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CalibriCore\CalibriCore.csproj" />
    <ProjectReference Include="..\CalibriDevices\CalibriDevices.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Configs\**\*.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="Configs\Recipes\Recipe_HuH_Load_60V_Voltage.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\TestBenches\RealRecept.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
